server:
  host: "localhost"
  port: 8084
  jwt_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0LWNsaWVudCIsImF1ZCI6InJlbGF5LWNsaWVudCIsImlzcyI6Imh0dHBzOi8vZWRnZS4yZ2MucnUvcmVhbG1zL2Nsb3VkYnJpZGdlIiwiZXhwIjoxNzUyMDIxODMyLCJpYXQiOjE3NTIwMTgyMzJ9.GsCE5Li-mg819Fp2SMoK4G4vQG2VQLCh0hmiUKLbiPc"

tls:
  enabled: false
  cert_file: ""
  key_file: ""
  ca_file: ""

auth:
  secret: ""

tunnel:
  local_port: 3389
  reconnect_delay: 5
  max_retries: 3

logging:
  level: "debug"
  file: "/var/log/cloudbridge-client/client.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true 