# Test Configuration for CloudBridge Client

# TLS Configuration
tls:
  enabled: false
  cert_file: ""
  key_file: ""
  ca_file: ""

# Server Configuration
server:
  host: localhost
  port: 8082
  jwt_token: "test-token"

# Auth Configuration
auth:
  secret: "test-token"

# Tunnel Configuration
tunnel:
  local_port: 3389
  reconnect_delay: 5
  max_retries: 3

# Metrics Configuration
metrics:
  enabled: true
  port: 9091
  path: "/metrics"
  interval: "15s"

# Health Configuration
health:
  enabled: true
  path: "/health"
  check_interval: "30s"

# Logging Configuration
logging:
  level: "info"
  file: "/tmp/cloudbridge-client-test.log"
  max_size: 10
  max_backups: 3
  max_age: 28
  compress: true
  format: "json"

# Protocol Configuration
protocol:
  version: "2.0"
  features: ["health_checks", "metrics"]

# Tenant Configuration
tenant:
  id: "test-tenant"
  name: "Test Tenant" 