# CloudBridge Client v2.0 Configuration
# Compatible with Relay Server v2.0

# TLS Configuration
tls:
  enabled: true
  cert_file: "/etc/cloudbridge-client/certs/client.crt"
  key_file: "/etc/cloudbridge-client/certs/client.key"
  ca_file: "/etc/cloudbridge-client/certs/ca.crt"

# Server Configuration
server:
  host: "relay.example.com"
  port: 8443
  jwt_token: "your-jwt-token-here"

# Authentication Configuration
auth:
  secret: "your-auth-secret"

# Tunnel Configuration
tunnel:
  local_port: 3389
  reconnect_delay: 5
  max_retries: 3

# Logging Configuration
logging:
  level: "info"
  file: "/var/log/cloudbridge-client/client.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Protocol Configuration (v2.0)
protocol:
  version: "2.0"
  features:
    - "tls"
    - "heartbeat"
    - "tunnel_info"
    - "multi_tenant"
    - "proxy"
    - "quic"
    - "metrics"

# Tenant Configuration (v2.0)
tenant:
  id: "tenant_001"
  name: "Example Tenant"

# Advanced Configuration
advanced:
  # Metrics Configuration
  metrics:
    enabled: true
    prometheus_port: 9090
    prometheus_path: "/metrics"
  
  # Health Check Configuration
  health_checks:
    enabled: true
    interval: "30s"
    timeout: "10s"
    checks:
      - name: "connection"
        type: "ping"
        target: "relay.example.com:8443"
      - name: "protocol"
        type: "custom"
        description: "Protocol availability check"
  
  # Circuit Breaker Configuration
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: "60s"
    half_open_max_requests: 3
  
  # Rate Limiting Configuration
  rate_limiting:
    enabled: true
    requests_per_second: 100
    burst_size: 50
  
  # QUIC Configuration
  quic:
    enabled: true
    max_streams: 100
    keep_alive_interval: "30s"
    idle_timeout: "60s"
    handshake_timeout: "10s"
  
  # HTTP/2 Configuration
  http2:
    enabled: true
    max_idle_conns: 100
    idle_conn_timeout: "90s"
    keep_alive: true
    keep_alive_period: "30s"
  
  # Connection Pooling
  connection_pool:
    enabled: true
    max_connections: 50
    max_idle_connections: 10
    connection_lifetime: "300s"
  
  # Retry Configuration
  retry:
    max_attempts: 3
    backoff_multiplier: 2.0
    initial_delay: "1s"
    max_delay: "30s"
  
  # Timeout Configuration
  timeouts:
    connect: "10s"
    read: "30s"
    write: "30s"
    idle: "60s"
  
  # Security Configuration
  security:
    tls_min_version: "1.2"
    tls_cipher_suites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    certificate_verification: true
    insecure_skip_verify: false
  
  # Monitoring Configuration
  monitoring:
    # Prometheus Metrics
    prometheus:
      enabled: true
      port: 9090
      path: "/metrics"
      collect_interval: "15s"
    
    # Health Checks
    health:
      enabled: true
      port: 8080
      path: "/health"
      interval: "30s"
      timeout: "10s"
    
    # Logging
    logging:
      level: "info"
      format: "json"
      include_metadata: true
    
    # Tracing
    tracing:
      enabled: false
      jaeger_endpoint: "http://jaeger:14268/api/traces"
      sampling_rate: 0.1

# Environment-specific overrides
environments:
  development:
    server:
      host: "localhost"
      port: 8080
    tls:
      enabled: false
    logging:
      level: "debug"
  
  staging:
    server:
      host: "staging-relay.example.com"
      port: 8443
    logging:
      level: "info"
  
  production:
    server:
      host: "relay.example.com"
      port: 8443
    logging:
      level: "warn"
    advanced:
      security:
        insecure_skip_verify: false
      monitoring:
        tracing:
          enabled: true
          sampling_rate: 0.01 