# CloudBridge Client Configuration

# TLS Configuration
tls:
  enabled: false
  cert_file: ""
  key_file: ""
  ca_file: ""

# Server Configuration
server:
  host: edge.2gc.ru
  port: 3456  # Relay Server (основной) порт для туннелирования
  jwt_token: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJJekdjc3NQSlpTQkRpbUx4cmx6WWdpWVBDTlBUSm45NkptVVZmcm9wQThRIn0.eyJleHAiOjE3NTIwNDkzNDAsImlhdCI6MTc1MjA0OTA0MCwianRpIjoidHJydGNjOjgwMjcxOGNlLTgxN2YtMDMyNy01YzllLTg4ZGRhZjU5YTU3ZCIsImlzcyI6Imh0dHBzOi8vZWRnZS4yZ2MucnUvcmVhbG1zL2Nsb3VkYnJpZGdlIiwiYXVkIjpbInJlbGF5LWNsaWVudCIsImFjY291bnQiXSwic3ViIjoiYTFiZWQyNmEtZDRkMi00OWIyLWFjMDctY2IwNDczMTA3MGNlIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicmVsYXktY2xpZW50IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2VkZ2UuMmdjLnJ1OjUxNzMiLCJodHRwczovL2VkZ2UuMmdjLnJ1OjgwODMiLCJodHRwczovL2VkZ2UuMmdjLnJ1Il0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWNsb3VkYnJpZGdlIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwicmVsYXktY2xpZW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwidW1hX3Byb3RlY3Rpb24iLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImNsaWVudEhvc3QiOiI4OS4yMDguODYuMTUwIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtcmVsYXktY2xpZW50IiwiY2xpZW50QWRkcmVzcyI6Ijg5LjIwOC44Ni4xNTAiLCJjbGllbnRfaWQiOiJyZWxheS1jbGllbnQifQ.ZP2uyDhx1ItpmhAnWhM3xW-A5uYvyF7kHzcSJSPQAPGRl1IqC3B1GBDyRxFERq7TAgdA1lc3SVm_02IXYSE_uUMsrLQFBq0L3L3APyVCpNdbY2vZgev1tCCDPdmXeAHiWxahkOIgcC4WUnXm5ZEjOnxkPPe1ZCh0s-8o8I_QZZWmjsYZYQborOJCbUgE5T3uUgsXZVVMBMMvzs2Yhac6K-c9j2i8w6mRKhx5ow41MYvuqKEUZYImI7J0tdWPDkoCX_cAbvVOFKXEyz0Nrcr5Mphct_TyO84KpaIOGXr15Goei_QHm47EhAG3lDP8IK55esgjQRh1K5GH6KnU1KU2ew"

# Tunnel Configuration
tunnel:
  local_port: 3389
  reconnect_delay: 5  # seconds
  max_retries: 3

# Metrics Configuration
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  interval: 15s

# Health Configuration
health:
  enabled: true
  path: "/health"
  check_interval: 30s

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error
  file: "/var/log/cloudbridge-client/client.log"
  max_size: 10    # MB
  max_backups: 3
  max_age: 28     # days
  compress: true
  format: "json" 