global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'relay-client'
    static_configs:
      - targets: ['edge.2gc.ru:9090']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'relay-client-health'
    static_configs:
      - targets: ['edge.2gc.ru:9090']
    metrics_path: '/health'
    scheme: 'http' 