name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create checksums
        run: |
          cd dist
          find . -type f -not -path "*/\.*" -exec sha256sum {} \; > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/checksums.txt
            dist/*.zip
            dist/*.tar.gz
            dist/*.exe
            dist/*/cloudbridge-client*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 