name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GO_VERSION: '1.21'
  CGO_ENABLED: 0

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            artifact_name: cloudbridge-client-linux-amd64
          - os: windows-latest
            goos: windows
            artifact_name: cloudbridge-client-windows-amd64.exe
          - os: macos-latest
            goos: darwin
            artifact_name: cloudbridge-client-darwin-amd64

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV
          echo "version=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT

      - name: Build
        shell: bash
        run: |
          GOOS=${{ matrix.goos }} \
          GOARCH=amd64 \
          go build -v -ldflags "-X main.Version=${VERSION}" -o ${{ matrix.artifact_name }} ./cmd/cloudbridge-client

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create checksums
        run: |
          cd artifacts
          sha256sum * > checksums.txt

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/cloudbridge-client-linux-amd64
            artifacts/cloudbridge-client-windows-amd64.exe
            artifacts/cloudbridge-client-darwin-amd64
            artifacts/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload source code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain

      - name: Upload source code (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/cloudbridge-client-linux-amd64
          asset_name: cloudbridge-client-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload source code (tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/cloudbridge-client-windows-amd64.exe
          asset_name: cloudbridge-client-windows-amd64.exe
          asset_content_type: application/octet-stream 